In [11]:
from fastai.tabular.all import *

path = untar_data(URLs.ADULT_SAMPLE)
path

Path('/Users/mohitsakhuja/.fastai/data/adult_sample')

In [12]:
dls = TabularDataLoaders.from_csv(
    path / "adult.csv",
    path=path,
    y_names="salary",
    cat_names=[
        "workclass",
        "education",
        "marital-status",
        "occupation",
        "relationship",
        "race",
    ],
    cont_names=["age", "fnlwgt", "education-num"],
    procs=[Categorify, FillMissing, Normalize],
    seed=42,
    bs=512,
)

dls.show_batch(max_n=6)

/Users/mohitsakhuja/Documents/personal/deep-learning-for-coders/.venv/lib/python3.13/site-packages/fastai/tabular/core.py:314: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  to[n].fillna(self.na_dict[n], inplace=True)

In [13]:
# Check and set device type as per architecture
import torch

device_type = (
    "cuda"
    if torch.cuda.is_available()
    else "mps" if torch.backends.mps.is_available() else "cpu"
)
device = torch.device(device_type)

device_type

'mps'

In [14]:
learner = tabular_learner(
    dls,
    metrics=accuracy,
)

learner.model.to(device)

learner.fit_one_cycle(4)

In [15]:
learner.show_results()